import ReadWindowTrimmer

/-!
# Proof certificate: read-window trimmer

GENERATED by alignment/checks/gen_certificates.py — do not edit by hand.
Read the output of `lake env lean <this file>`: every `#check` line shows a
theorem statement, every `depends on axioms` line must list only propext,
Classical.choice, Quot.sound (never sorryAx).  `example` lines pin the
exported statements verbatim (they come from KERNEL_THEOREMS in
pabench/run_all.py, the table the comparison harness re-elaborates per commit).
-/

-- ── supporting (ReadWindowTrimmer): every optimized trimmer equals the frozen get_best_window ──
#check @ReadWindow.getBestWindowIncremental_equals_frozen_get_best_window
#print axioms ReadWindow.getBestWindowIncremental_equals_frozen_get_best_window
#check @ReadWindow.getBestWindowLinear_equals_frozen_get_best_window
#print axioms ReadWindow.getBestWindowLinear_equals_frozen_get_best_window
#check @ReadWindow.getBestWindowFused_equals_frozen_get_best_window
#print axioms ReadWindow.getBestWindowFused_equals_frozen_get_best_window
#check @ReadWindow.getBestWindowFlat_equals_frozen_get_best_window
#print axioms ReadWindow.getBestWindowFlat_equals_frozen_get_best_window
#check @ReadWindow.getBestWindowFoldr_equals_frozen_get_best_window
#print axioms ReadWindow.getBestWindowFoldr_equals_frozen_get_best_window
#check @ReadWindow.getBestWindowPacked_equals_frozen_get_best_window
#print axioms ReadWindow.getBestWindowPacked_equals_frozen_get_best_window
