import AlignmentCompact
import AlignmentSmallErrors
open AlignmentSpec

/-!
# Proof certificate: codec folder `wfa_small_errors`

GENERATED by alignment/checks/gen_certificates.py — do not edit by hand.
Read the output of `lake env lean <this file>`: every `#check` line shows a
theorem statement, every `depends on axioms` line must list only propext,
Classical.choice, Quot.sound (never sorryAx).  `example` lines pin the
exported statements verbatim (they come from KERNEL_THEOREMS in
pabench/run_all.py, the table the comparison harness re-elaborates per commit).
* runner kernel `wfahc` (module `AlignmentCompact`): the codec's score equals the frozen optimum; every returned walk is a valid alignment carrying its true score; a result is always returned
* runner kernel `wfah` (module `AlignmentSmallErrors`): the codec's score equals the frozen optimum; every returned walk is a valid alignment carrying its true score; a result is always returned
-/

-- ══ exported: kernel wfahc (score) — statements pinned ══
example : ∀ (sc : Scoring) (xa ya : Array Char), (wfaAlignHC sc xa ya).map Prod.snd = (getBestAlignment sc xa.toList ya.toList).map Prod.snd :=
  wfaAlignHC_score
#print axioms wfaAlignHC_score

example : ∀ (sc : Scoring) (xa ya : Array Char) (c : Array (Step × Nat)) (s : Int), wfaAlignHC sc xa ya = some (c, s) → IsMonotoneWalk (expandCigar c) xa.toList ya.toList ∧ walkScore sc xa.toList ya.toList (expandCigar c) = s :=
  wfaAlignHC_sound
#print axioms wfaAlignHC_sound

example : ∀ (sc : Scoring) (xa ya : Array Char), (wfaAlignHC sc xa ya).isSome :=
  wfaAlignHC_isSome
#print axioms wfaAlignHC_isSome

-- ══ exported: kernel wfah (score) — statements pinned ══
example : ∀ (sc : Scoring) (xa ya : Array Char), (wfaAlignH sc xa ya).map Prod.snd = (getBestAlignment sc xa.toList ya.toList).map Prod.snd :=
  wfaAlignH_score
#print axioms wfaAlignH_score

example : ∀ (sc : Scoring) (xa ya : Array Char) (w : List Step) (s : Int), wfaAlignH sc xa ya = some (w, s) → IsMonotoneWalk w xa.toList ya.toList ∧ walkScore sc xa.toList ya.toList w = s :=
  wfaAlignH_sound
#print axioms wfaAlignH_sound

example : ∀ (sc : Scoring) (xa ya : Array Char), (wfaAlignH sc xa ya).isSome :=
  wfaAlignH_isSome
#print axioms wfaAlignH_isSome

-- ── supporting (AlignmentSmallErrors): equal lengths, ≤2 substitutions: a checked diagonal walk is optimal ──
#check @gapless_eq_diags
#print axioms gapless_eq_diags
#check @two_errors_optimal
#print axioms two_errors_optimal
#check @diagCheckA_sound
#print axioms diagCheckA_sound
#check @smallDiag_spec
#print axioms smallDiag_spec

-- ── supporting (AlignmentCompact): compact (run-length) output expands to the proven result ──
#check @expand_unitCigar
#print axioms expand_unitCigar
#check @compactSmall_refines
#print axioms compactSmall_refines
#check @wfaAlignHC_refines
#print axioms wfaAlignHC_refines
