import AlignmentExchange
import AlignmentWfa
open AlignmentSpec

/-!
# Proof certificate: codec folder `wfa`

GENERATED by alignment/checks/gen_certificates.py — do not edit by hand.
Read the output of `lake env lean <this file>`: every `#check` line shows a
theorem statement, every `depends on axioms` line must list only propext,
Classical.choice, Quot.sound (never sorryAx).  `example` lines pin the
exported statements verbatim (they come from KERNEL_THEOREMS in
pabench/run_all.py, the table the comparison harness re-elaborates per commit).
* runner kernel `wfa` (module `AlignmentWfa`): the codec's score equals the frozen optimum; every returned walk is a valid alignment carrying its true score; a result is always returned
-/

-- ══ exported: kernel wfa (score) — statements pinned ══
example : ∀ (sc : Scoring) (xs ys : List Char), (wfaAlign sc xs ys).map (fun r => r.2) = (getBestAlignment sc xs ys).map (fun r => r.2) :=
  wfaAlign_score
#print axioms wfaAlign_score

example : ∀ (sc : Scoring) (xs ys : List Char) (w : List Step) (s : Int), wfaAlign sc xs ys = some (w, s) → IsMonotoneWalk w xs ys ∧ walkScore sc xs ys w = s :=
  wfaAlign_sound
#print axioms wfaAlign_sound

example : ∀ (sc : Scoring) (xs ys : List Char), (wfaAlign sc xs ys).isSome :=
  wfaAlign_isSome
#print axioms wfaAlign_isSome

-- ── supporting (AlignmentExchange): greedy match-extension lemma (WFA's free extension) at the spec level ──
#check @bellmanAux_match_extend
#print axioms bellmanAux_match_extend
#check @bellmanAux_match_extend_none
#print axioms bellmanAux_match_extend_none
#check @getBestAlignment_match_extend
#print axioms getBestAlignment_match_extend

-- ── supporting (AlignmentWfa): model soundness + completeness, optimality of the loop, banded/array refinements, gate ──
#check @seedLevel_sound
#print axioms seedLevel_sound
#check @nextLevel_sound
#print axioms nextLevel_sound
#check @wfaRun_sound
#print axioms wfaRun_sound
#check @seedLevel_complete
#print axioms seedLevel_complete
#check @nextLevel_complete
#print axioms nextLevel_complete
#check @wfaLoop_opt
#print axioms wfaLoop_opt
#check @wfaRun_opt
#print axioms wfaRun_opt
#check @wfaRunT_eq
#print axioms wfaRunT_eq
#check @wfaRunA_eq
#print axioms wfaRunA_eq
#check @wfaGate_spec
#print axioms wfaGate_spec
