import AlignmentWfaView

/-! Generated by generate_wfa_direct.py. Three materialized arrays, scalar
captures only. Each component is checked against the proved view algebra. -/
namespace AlignmentSpec
set_option maxHeartbeats 1000000
set_option maxRecDepth 10000

def directX (m n : Nat) (xe xo : RFront) : RFront :=
  let v0 := xe.lo + 1
  let v1 := xo.lo + 1
  let v2 := min v0 v1
  let v3 := v0 - v2
  let v4 := v1 - v2
  let v5 := if xe.body.size = 0 then v1 else if xo.body.size = 0 then v0 else v2
  let v6 := if xe.body.size = 0 then xo.body.size else if xo.body.size = 0 then xe.body.size else max (v3 + xe.body.size) (v4 + xo.body.size)
  let out : RFront := ⟨v5, arrayBuild (fun i : Fin v6 => (if xe.body.size = 0 then pushXR m n (xo.lo + i.val) ((xo.body[i.val]?).getD 0) else if xo.body.size = 0 then pushXR m n (xe.lo + i.val) ((xe.body[i.val]?).getD 0) else betterR (if i.val < v3 + xe.body.size then (if i.val < v3 then 0 else pushXR m n (xe.lo + (i.val - v3)) ((xe.body[(i.val - v3)]?).getD 0)) else 0) (if i.val < v4 + xo.body.size then (if i.val < v4 then 0 else pushXR m n (xo.lo + (i.val - v4)) ((xo.body[(i.val - v4)]?).getD 0)) else 0)))⟩
  out

theorem directX_eq (m n : Nat) (xe xo : RFront) :
    directX m n xe xo = packV (zipV (shiftUpV (mapV (pushXR m n) (viewR xe))) (shiftUpV (mapV (pushXR m n) (viewR xo)))) := by
  rfl

def directY (m n len : Nat) (ye yo : RFront) : RFront :=
  let v0 := ye.lo - 1
  let v1 := if ye.lo = 0 then min (1 + (len - 1)) ye.body.size - 1 else if ye.body.size ≤ len - ye.lo then ye.body.size else min (len - ye.lo) ye.body.size
  let v2 := yo.lo - 1
  let v3 := if yo.lo = 0 then min (1 + (len - 1)) yo.body.size - 1 else if yo.body.size ≤ len - yo.lo then yo.body.size else min (len - yo.lo) yo.body.size
  let v4 := min v0 v2
  let v5 := v0 - v4
  let v6 := v2 - v4
  let v7 := if v1 = 0 then v2 else if v3 = 0 then v0 else v4
  let v8 := if v1 = 0 then v3 else if v3 = 0 then v1 else max (v5 + v1) (v6 + v3)
  let out : RFront := ⟨v7, arrayBuild (fun i : Fin v8 => (if v1 = 0 then pushYR m n (yo.lo + (if yo.lo = 0 then 1 + i.val else i.val)) ((yo.body[(if yo.lo = 0 then 1 + i.val else i.val)]?).getD 0) else if v3 = 0 then pushYR m n (ye.lo + (if ye.lo = 0 then 1 + i.val else i.val)) ((ye.body[(if ye.lo = 0 then 1 + i.val else i.val)]?).getD 0) else betterR (if i.val < v5 + v1 then (if i.val < v5 then 0 else pushYR m n (ye.lo + (if ye.lo = 0 then 1 + (i.val - v5) else (i.val - v5))) ((ye.body[(if ye.lo = 0 then 1 + (i.val - v5) else (i.val - v5))]?).getD 0)) else 0) (if i.val < v6 + v3 then (if i.val < v6 then 0 else pushYR m n (yo.lo + (if yo.lo = 0 then 1 + (i.val - v6) else (i.val - v6))) ((yo.body[(if yo.lo = 0 then 1 + (i.val - v6) else (i.val - v6))]?).getD 0)) else 0)))⟩
  out

theorem directY_eq (m n len : Nat) (ye yo : RFront) :
    directY m n len ye yo = packV (zipV (shiftDownV len (mapV (pushYR m n) (viewR ye))) (shiftDownV len (mapV (pushYR m n) (viewR yo)))) := by
  rfl

def directM (m n : Nat) (xa ya : Array Char) (dm xf yf : RFront) : RFront :=
  let v0 := min dm.lo xf.lo
  let v1 := dm.lo - v0
  let v2 := xf.lo - v0
  let v3 := if dm.body.size = 0 then xf.lo else if xf.body.size = 0 then dm.lo else v0
  let v4 := if dm.body.size = 0 then xf.body.size else if xf.body.size = 0 then dm.body.size else max (v1 + dm.body.size) (v2 + xf.body.size)
  let v5 := min v3 yf.lo
  let v6 := v3 - v5
  let v7 := yf.lo - v5
  let v8 := if v4 = 0 then yf.lo else if yf.body.size = 0 then v3 else v5
  let v9 := if v4 = 0 then yf.body.size else if yf.body.size = 0 then v4 else max (v6 + v4) (v7 + yf.body.size)
  let out : RFront := ⟨v8, arrayBuild (fun i : Fin v9 => extR m xa ya (v8 + i.val) ((if v4 = 0 then (yf.body[i.val]?).getD 0 else if yf.body.size = 0 then (if dm.body.size = 0 then (xf.body[i.val]?).getD 0 else if xf.body.size = 0 then pushDR m n (dm.lo + i.val) ((dm.body[i.val]?).getD 0) else betterR (if i.val < v1 + dm.body.size then (if i.val < v1 then 0 else pushDR m n (dm.lo + (i.val - v1)) ((dm.body[(i.val - v1)]?).getD 0)) else 0) (if i.val < v2 + xf.body.size then (if i.val < v2 then 0 else (xf.body[(i.val - v2)]?).getD 0) else 0)) else betterR (if i.val < v6 + v4 then (if i.val < v6 then 0 else (if dm.body.size = 0 then (xf.body[(i.val - v6)]?).getD 0 else if xf.body.size = 0 then pushDR m n (dm.lo + (i.val - v6)) ((dm.body[(i.val - v6)]?).getD 0) else betterR (if (i.val - v6) < v1 + dm.body.size then (if (i.val - v6) < v1 then 0 else pushDR m n (dm.lo + ((i.val - v6) - v1)) ((dm.body[((i.val - v6) - v1)]?).getD 0)) else 0) (if (i.val - v6) < v2 + xf.body.size then (if (i.val - v6) < v2 then 0 else (xf.body[((i.val - v6) - v2)]?).getD 0) else 0))) else 0) (if i.val < v7 + yf.body.size then (if i.val < v7 then 0 else (yf.body[(i.val - v7)]?).getD 0) else 0))))⟩
  out

theorem directM_eq (m n : Nat) (xa ya : Array Char) (dm xf yf : RFront) :
    directM m n xa ya dm xf yf = packV (mapV (extR m xa ya) (zipV (zipV (mapV (pushDR m n) (viewR dm)) (viewR xf)) (viewR yf))) := by
  rfl

def nextLevelD (m n : Nat) (xa ya : Array Char) (len pe po px : Nat)
    (hist : List RLevel) : RLevel :=
  let xf := directX m n (frontAtR hist pe (·.xf)) (frontAtR hist po (·.mf))
  let yf := directY m n len (frontAtR hist pe (·.yf)) (frontAtR hist po (·.mf))
  ⟨directM m n xa ya (frontAtR hist px (·.mf)) xf yf, xf, yf⟩

theorem nextLevelD_eq (m n : Nat) (xa ya : Array Char) (len pe po px : Nat)
    (hist : List RLevel) :
    nextLevelD m n xa ya len pe po px hist = nextLevelR m n xa ya len pe po px hist := by
  simp only [nextLevelD, directX_eq, directY_eq, directM_eq]
  exact nextLevelV_eq m n xa ya len pe po px hist

end AlignmentSpec
#print axioms AlignmentSpec.nextLevelD_eq
