import AlignmentWfaU32
import AlignmentWfaU32Ext
import AlignmentWfaU32Fill
import AlignmentWfaU32FillSSpec
import AlignmentWfaU32FillSpec
import AlignmentWfaU32FillSpec3
import AlignmentWfaU32Kernel2
import AlignmentWfaU32Kernel3
import WfaU3
import AlignmentWfaU32Lattice
import AlignmentWfaU32Level
import AlignmentWfaU32Level2
import AlignmentWfaU32Level3
import AlignmentWfaU32LevelS
import AlignmentWfaU32Loop
import AlignmentWfaU32Loop3
import AlignmentWfaU32Single
import AlignmentWfaU32Step
open AlignmentSpec

/-!
# Proof certificate: codec folder `wfa_u32` — PARTIAL FOUNDATIONS, NO ALIGNMENT OPTIMALITY CLAIM

GENERATED by alignment/checks/gen_certificates.py — do not edit by hand.
Read the output of `lake env lean <this file>`: every `#check` line shows a
theorem statement, every `depends on axioms` line must list only propext,
Classical.choice, Quot.sound (never sorryAx).  `example` lines pin the
exported statements verbatim (they come from KERNEL_THEOREMS in
pabench/run_all.py, the table the comparison harness re-elaborates per commit).
* runner kernel `wfau` (module `AlignmentWfaU32`): the codec's score equals the frozen optimum; every returned walk is a valid alignment carrying its true score; a result is always returned
* runner kernel `wfau2` (module `AlignmentWfaU32Kernel2`): the codec's score equals the frozen optimum; every returned walk is a valid alignment carrying its true score; a result is always returned
* runner kernel `wfau3` (module `AlignmentWfaU32Kernel3`): the codec's score equals the frozen optimum; every returned walk is a valid alignment carrying its true score; a result is always returned
-/

-- ══ exported: kernel wfau (score) — statements pinned ══
example : ∀ (sc : Scoring) (xa ya : Array Char), (wfaAlignU sc xa ya).map Prod.snd = (getBestAlignment sc xa.toList ya.toList).map Prod.snd :=
  wfaAlignU_score
#print axioms wfaAlignU_score

example : ∀ (sc : Scoring) (xa ya : Array Char) (c : Array (Step × Nat)) (s : Int), wfaAlignU sc xa ya = some (c, s) → IsMonotoneWalk (expandCigar c) xa.toList ya.toList ∧ walkScore sc xa.toList ya.toList (expandCigar c) = s :=
  wfaAlignU_sound
#print axioms wfaAlignU_sound

example : ∀ (sc : Scoring) (xa ya : Array Char), (wfaAlignU sc xa ya).isSome :=
  wfaAlignU_isSome
#print axioms wfaAlignU_isSome

-- ══ exported: kernel wfau2 (score) — statements pinned ══
example : ∀ (sc : Scoring) (xa ya : Array Char), (wfaAlignU2 sc xa ya).map Prod.snd = (getBestAlignment sc xa.toList ya.toList).map Prod.snd :=
  wfaAlignU2_score
#print axioms wfaAlignU2_score

example : ∀ (sc : Scoring) (xa ya : Array Char) (c : Array (Step × Nat)) (s : Int), wfaAlignU2 sc xa ya = some (c, s) → IsMonotoneWalk (expandCigar c) xa.toList ya.toList ∧ walkScore sc xa.toList ya.toList (expandCigar c) = s :=
  wfaAlignU2_sound
#print axioms wfaAlignU2_sound

example : ∀ (sc : Scoring) (xa ya : Array Char), (wfaAlignU2 sc xa ya).isSome :=
  wfaAlignU2_isSome
#print axioms wfaAlignU2_isSome

-- ══ exported: kernel wfau3 (score) — statements pinned ══
example : ∀ (sc : Scoring) (xa ya : Array Char), (match wfaAlignU3 sc xa ya with | some result => some result.2 | none => none) = (match getBestAlignment sc xa.toList ya.toList with | some result => some result.2 | none => none) :=
  wfaAlignU3_score
#print axioms wfaAlignU3_score

example : ∀ (sc : Scoring) (xa ya : Array Char) (c : Array (Step × Nat)) (s : Int), wfaAlignU3 sc xa ya = some (c, s) → IsMonotoneWalk (expandCigar c) xa.toList ya.toList ∧ walkScore sc xa.toList ya.toList (expandCigar c) = s :=
  wfaAlignU3_sound
#print axioms wfaAlignU3_sound

example : ∀ (sc : Scoring) (xa ya : Array Char), (wfaAlignU3 sc xa ya).isSome :=
  wfaAlignU3_isSome
#print axioms wfaAlignU3_isSome

-- ── supporting (AlignmentWfaU32Level): bounded UInt32 arithmetic = Nat code arithmetic below 2^30 (saturating usub, no geometric invariant) ──
#check @U32Proof.usub_toNat
#print axioms U32Proof.usub_toNat
#check @U32Proof.ubetter_toNat
#print axioms U32Proof.ubetter_toNat
#check @U32Proof.ujoff_toNat
#print axioms U32Proof.ujoff_toNat
#check @U32Proof.upushX_toNat
#print axioms U32Proof.upushX_toNat
#check @U32Proof.upushY_toNat
#print axioms U32Proof.upushY_toNat
#check @U32Proof.upushD_toNat
#print axioms U32Proof.upushD_toNat
#check @U32Proof.lcpArr_le
#print axioms U32Proof.lcpArr_le
#check @U32Proof.uext_toNat
#print axioms U32Proof.uext_toNat
#check @U32Proof.betterR_valid
#print axioms U32Proof.betterR_valid
#check @U32Proof.pushXR_valid
#print axioms U32Proof.pushXR_valid
#check @U32Proof.pushYR_valid
#print axioms U32Proof.pushYR_valid
#check @U32Proof.pushDR_valid
#print axioms U32Proof.pushDR_valid

-- ── supporting (AlignmentWfaU32Step): padded UInt32 level step denotes nextLevelR (all three fronts), well-formedness preserved, corner test = cornerO ──
#check @U32Proof.rget_toRF
#print axioms U32Proof.rget_toRF
#check @U32Proof.uFillGo_spec
#print axioms U32Proof.uFillGo_spec
#check @U32Proof.uLevel_fronts
#print axioms U32Proof.uLevel_fronts
#check @U32Proof.uget_uLevel_xf
#print axioms U32Proof.uget_uLevel_xf
#check @U32Proof.uget_uLevel_yf
#print axioms U32Proof.uget_uLevel_yf
#check @U32Proof.uget_uLevel_mf
#print axioms U32Proof.uget_uLevel_mf
#check @U32Proof.wf_uLevel
#print axioms U32Proof.wf_uLevel
#check @U32Proof.rdenF_ext
#print axioms U32Proof.rdenF_ext
#check @U32Proof.rdenL_toRLevel_uLevel
#print axioms U32Proof.rdenL_toRLevel_uLevel
#check @U32Proof.cornerU_eq
#print axioms U32Proof.cornerU_eq
#check @U32Proof.cornerU_eq_cornerO
#print axioms U32Proof.cornerU_eq_cornerO

-- ── supporting (AlignmentWfaU32Loop): UInt32 loop and run = the offsets-only proven loop (wfaLoopO / wfaRunO) ──
#check @U32Proof.udenL_uLevel
#print axioms U32Proof.udenL_uLevel
#check @U32Proof.uLoop_eq
#print axioms U32Proof.uLoop_eq
#check @U32Proof.wf_seedU
#print axioms U32Proof.wf_seedU
#check @U32Proof.udenL_seedU
#print axioms U32Proof.udenL_seedU
#check @U32Proof.uRun_eq
#print axioms U32Proof.uRun_eq

-- ── supporting (AlignmentWfaU32): runtime certificate (fast checker + offsets identity) ⇒ optimal score; function equality with wfaAlign ──
#check @certifiedRunsU_spec
#print axioms certifiedRunsU_spec
#check @wfaAlignU_score_eq_wfaAlign
#print axioms wfaAlignU_score_eq_wfaAlign
#check @wfaAlignU_score_fun_eq
#print axioms wfaAlignU_score_fun_eq

-- ── supporting (AlignmentWfaU32Fill): hot loop of the second kernel: USize LCP loop = spec lcp ──
#check @U32Proof.lcpU_toNat
#print axioms U32Proof.lcpU_toNat

-- ── supporting (AlignmentWfaU32Ext): inline-compare extension = the proven extension ──
#check @U32Proof.uext2_eq
#print axioms U32Proof.uext2_eq

-- ── supporting (AlignmentWfaU32FillSpec): the uget/uset cell loop writes exactly the cell values ──
#check @U32Proof.uFillGo2_spec
#print axioms U32Proof.uFillGo2_spec

-- ── supporting (AlignmentWfaU32Level2): a level the hot loop returns is the proven builder's level, array for array ──
#check @U32Proof.uLevel2Body_eq
#print axioms U32Proof.uLevel2Body_eq
#check @U32Proof.uLevel2_some
#print axioms U32Proof.uLevel2_some

-- ── supporting (AlignmentWfaU32Lattice): penalties divided by their gcd: the divided run's corner level times g is the original run's ──
#check @U32Proof.gcdU_eq
#print axioms U32Proof.gcdU_eq
#check @U32Proof.nextLevelO_empty
#print axioms U32Proof.nextLevelO_empty
#check @U32Proof.wfaLoopO_fuel_mono
#print axioms U32Proof.wfaLoopO_fuel_mono
#check @U32Proof.loop_lattice
#print axioms U32Proof.loop_lattice
#check @U32Proof.wfaRunO_lattice
#print axioms U32Proof.wfaRunO_lattice

-- ── supporting (AlignmentWfaU32Single): single-source lemmas: X ≤ M, Y ≤ M on every level, pushes monotone, pointX/pointY from the M front alone ──
#check @U32Proof.pushXR_mono
#print axioms U32Proof.pushXR_mono
#check @U32Proof.pushYR_mono
#print axioms U32Proof.pushYR_mono
#check @U32Proof.pointX_single
#print axioms U32Proof.pointX_single
#check @U32Proof.pointY_single
#print axioms U32Proof.pointY_single
#check @U32Proof.nextLevelR_xf_le_mf
#print axioms U32Proof.nextLevelR_xf_le_mf
#check @U32Proof.nextLevelR_yf_le_mf
#print axioms U32Proof.nextLevelR_yf_le_mf

-- ── supporting (AlignmentWfaU32FillSSpec): the single-source loop (one read per cell, two cells per iteration) writes exactly the cell values ──
#check @U32Proof.uFillS_spec
#print axioms U32Proof.uFillS_spec

-- ── supporting (AlignmentWfaU32LevelS): single-source level: the built M front denotes nextLevelR's M front under the X ≤ M invariant ──
#check @U32Proof.rget_nextLevelR_single
#print axioms U32Proof.rget_nextLevelR_single
#check @U32Proof.uCellS_toNat
#print axioms U32Proof.uCellS_toNat
#check @U32Proof.cellS_toNat
#print axioms U32Proof.cellS_toNat
#check @U32Proof.uLevelS_some
#print axioms U32Proof.uLevelS_some

-- ── supporting (AlignmentWfaU32Kernel2): second kernel: general and single-source loops/runs = the offsets run with divided penalties; certificate ⇒ optimal score; function equality with wfaAlign ──
#check @U32Proof.uLoop2_some
#print axioms U32Proof.uLoop2_some
#check @U32Proof.uRun2_some
#print axioms U32Proof.uRun2_some
#check @U32Proof.uLoopS_some
#print axioms U32Proof.uLoopS_some
#check @U32Proof.uRunS_some
#print axioms U32Proof.uRunS_some
#check @U32Proof.uRunD_some
#print axioms U32Proof.uRunD_some
#check @certifiedRunsU2_spec
#print axioms certifiedRunsU2_spec
#check @wfaAlignU2_score_eq_wfaAlign
#print axioms wfaAlignU2_score_eq_wfaAlign
#check @wfaAlignU2_score_fun_eq
#print axioms wfaAlignU2_score_fun_eq

-- ── supporting (AlignmentWfaU32FillSpec3): the block-layout cell loop (one array, three blocks) writes exactly the cell values ──
#check @U32Proof.uFillGo3_spec
#print axioms U32Proof.uFillGo3_spec

-- ── supporting (AlignmentWfaU32Loop3): block levels: the seed's view is seedU, the corner test is cornerU of the view, array history = list window ──
#check @U32Proof.toU_seedB
#print axioms U32Proof.toU_seedB
#check @U32Proof.corner3_eq
#print axioms U32Proof.corner3_eq
#check @U32Proof.srcRel_step
#print axioms U32Proof.srcRel_step

-- ── supporting (AlignmentWfaU32Level3): a block level the hot loop returns views to the proven builder's level, block for block ──
#check @U32Proof.uLevel3Body_eq
#print axioms U32Proof.uLevel3Body_eq
#check @U32Proof.uLevel3_some
#print axioms U32Proof.uLevel3_some

-- ── supporting (AlignmentWfaU32Kernel3): third kernel: block-layout loop/run = the offsets run with divided penalties; certificate ⇒ optimal score; function equality with wfaAlign ──
#check @U32Proof.uLoop3_some
#print axioms U32Proof.uLoop3_some
#check @U32Proof.uRun3_some
#print axioms U32Proof.uRun3_some
#check @certifiedRunsU3_spec
#print axioms certifiedRunsU3_spec
#check @wfaAlignU3_score_eq_wfaAlign
#print axioms wfaAlignU3_score_eq_wfaAlign
#check @wfaAlignU3_score_fun_eq
#print axioms wfaAlignU3_score_fun_eq
