import AlignmentCigarCheck

/-! Generated by generate_run_trace.py. Offset traceback emits whole diagonal
runs. Acceptance requires the run checker and an optimal-score certificate.
The underlying offset traceback follows WFA2; see AlignmentWfaCertified.lean.
-/
namespace AlignmentSpec
def traceRuns (m n : Nat) (pe po px : Nat) (hist : Array RLevel)
    (L : Nat) : List (Step × Nat) := Id.run do
  let mI : Int := m
  let nI : Int := n
  let get := fun (L' : Nat) (sel : RLevel → RFront) => sel hist[L']!
  let mut w : List (Step × Nat) := []      -- reversed walk (head = last step)
  let mut L := L
  let mut t := n
  let mut front : Nat := 0         -- 0 = mf, 1 = xf, 2 = yf
  let mut off : Int := rgetI (get L (·.mf)) n
  let mut fuel := 4 * (m + n) + 8
  while fuel > 0 do
    fuel := fuel - 1
    if front == 0 then
      -- mf cell: undo extension, then find base winner
      let x := rgetI (get L (·.xf)) t
      let y := rgetI (get L (·.yf)) t
      let s := if px ≤ L then rgetI (get (L - px) (·.mf)) t else -1
      let j := traceJoff mI t s
      let e : Int := if s < 0 then -1 else if s < mI && j < nI then s + 1
                     else if s ≥ 1 && j ≥ 1 then s else -1
      let b1 := if x ≤ e then e else x
      let b := if L == 0 then (0 : Int) else if y ≤ b1 then b1 else y
      -- extension steps
      let k := off - b
      if k > 0 then w := (.diag, k.toNat) :: w
      if L == 0 then break
      if b == e && (x ≤ e) && (y ≤ b1) then
        -- diagonal step from mf[L-px][t] (source offset s)
        if s < mI && j < nI then w := (.diag, 1) :: w
        else return [] -- request exact fallback when boundary surgery would be needed
        L := L - px; front := 0; off := s
      else if b == b1 then
        front := 1; off := x
      else
        front := 2; off := y
    else if front == 1 then
      -- xf[L][t] = better(gapX xf[L-pe][t-1], gapX mf[L-po][t-1])
      let sa := if pe ≤ L && t ≥ 1 then rgetI (get (L - pe) (·.xf)) (t - 1) else -1
      let sb := if po ≤ L && t ≥ 1 then rgetI (get (L - po) (·.mf)) (t - 1) else -1
      let ja := traceJoff mI (t - 1 : Nat) sa
      let jb := traceJoff mI (t - 1 : Nat) sb
      let a : Int := if sa < 0 then -1 else if ja < nI then sa else if sa ≥ 1 && ja ≥ 1 then sa - 1 else -1
      let b : Int := if sb < 0 then -1 else if jb < nI then sb else if sb ≥ 1 && jb ≥ 1 then sb - 1 else -1
      if b ≤ a then
        L := L - pe; front := 1; off := sa
        w := (.gapX, 1) :: w
      else
        L := L - po; front := 0; off := sb
        w := (.gapX, 1) :: w
      t := t - 1
    else
      let sa := if pe ≤ L && t + 1 < m + n + 1 then rgetI (get (L - pe) (·.yf)) (t + 1) else -1
      let sb := if po ≤ L && t + 1 < m + n + 1 then rgetI (get (L - po) (·.mf)) (t + 1) else -1
      let ja := traceJoff mI (t + 1) sa
      let jb := traceJoff mI (t + 1) sb
      let a : Int := if sa < 0 then -1 else if sa < mI then sa + 1 else if sa ≥ 1 && ja ≥ 1 then sa else -1
      let b : Int := if sb < 0 then -1 else if sb < mI then sb + 1 else if sb ≥ 1 && jb ≥ 1 then sb else -1
      if b ≤ a then
        L := L - pe; front := 2; off := sa
        w := (.gapY, 1) :: w
      else
        L := L - po; front := 0; off := sb
        w := (.gapY, 1) :: w
      t := t + 1
  return w

end AlignmentSpec
