import AlignmentAlgorithms
open AlignmentSpec

/-!
# Proof certificate: codec folder `gotoh`

GENERATED by alignment/checks/gen_certificates.py — do not edit by hand.
Read the output of `lake env lean <this file>`: every `#check` line shows a
theorem statement, every `depends on axioms` line must list only propext,
Classical.choice, Quot.sound (never sorryAx).  `example` lines pin the
exported statements verbatim (they come from KERNEL_THEOREMS in
pabench/run_all.py, the table the comparison harness re-elaborates per commit).
* runner kernel `gotoh` (module `AlignmentAlgorithms`): the codec's result (walk and score) EQUALS the frozen specification's result
-/

-- ══ exported: kernel gotoh (equality) — statements pinned ══
example : ∀ (sc : Scoring) (xs ys : List Char), gotohFusedAlign sc xs ys = getBestAlignment sc xs ys :=
  gotohFusedAlign_equals_getBestAlignment
#print axioms gotohFusedAlign_equals_getBestAlignment

-- ── supporting (AlignmentAlgorithms): Bellman/Gotoh table refinements of the frozen enumeration ──
#check @getBestAlignment_eq_bestAux
#print axioms getBestAlignment_eq_bestAux
#check @bestAux_eq_bellmanAux
#print axioms bestAux_eq_bellmanAux
#check @bellmanAlign_equals_getBestAlignment
#print axioms bellmanAlign_equals_getBestAlignment
#check @gotohTable_eq
#print axioms gotohTable_eq
#check @gotohAlign_equals_getBestAlignment
#print axioms gotohAlign_equals_getBestAlignment
#check @gotohFusedTable_eq
#print axioms gotohFusedTable_eq
