import AlignmentWfaFast
import AlignmentWfaFused
import AlignmentWfaLazy
import AlignmentWfaLazyLevel
open AlignmentSpec

/-!
# Proof certificate: codec folder `wfa_fast`

GENERATED by alignment/checks/gen_certificates.py — do not edit by hand.
Read the output of `lake env lean <this file>`: every `#check` line shows a
theorem statement, every `depends on axioms` line must list only propext,
Classical.choice, Quot.sound (never sorryAx).  `example` lines pin the
exported statements verbatim (they come from KERNEL_THEOREMS in
pabench/run_all.py, the table the comparison harness re-elaborates per commit).
* runner kernel `wfai` (module `AlignmentWfaFast`): the codec's score equals the frozen optimum; every returned walk is a valid alignment carrying its true score; a result is always returned
* runner kernel `wfaf` (module `AlignmentWfaFast`): the codec's score equals the frozen optimum; every returned walk is a valid alignment carrying its true score; a result is always returned
* runner kernel `wfal` (module `AlignmentWfaFast`): the codec's score equals the frozen optimum; every returned walk is a valid alignment carrying its true score; a result is always returned
-/

-- ══ exported: kernel wfai (score) — statements pinned ══
example : ∀ (sc : Scoring) (xs ys : List Char), wfaAlignI sc xs ys = wfaAlign sc xs ys :=
  wfaAlignI_eq
#print axioms wfaAlignI_eq

example : ∀ (sc : Scoring) (xs ys : List Char), (wfaAlignI sc xs ys).map (fun r => r.2) = (getBestAlignment sc xs ys).map (fun r => r.2) :=
  wfaAlignI_score
#print axioms wfaAlignI_score

example : ∀ (sc : Scoring) (xs ys : List Char) (w : List Step) (s : Int), wfaAlignI sc xs ys = some (w, s) → IsMonotoneWalk w xs ys ∧ walkScore sc xs ys w = s :=
  wfaAlignI_sound
#print axioms wfaAlignI_sound

example : ∀ (sc : Scoring) (xs ys : List Char), (wfaAlignI sc xs ys).isSome :=
  wfaAlignI_isSome
#print axioms wfaAlignI_isSome

-- ══ exported: kernel wfaf (score) — statements pinned ══
example : ∀ (sc : Scoring) (xs ys : List Char), wfaAlignF sc xs ys = wfaAlign sc xs ys :=
  wfaAlignF_eq
#print axioms wfaAlignF_eq

example : ∀ (sc : Scoring) (xs ys : List Char), (wfaAlignF sc xs ys).map (fun r => r.2) = (getBestAlignment sc xs ys).map (fun r => r.2) :=
  wfaAlignF_score
#print axioms wfaAlignF_score

example : ∀ (sc : Scoring) (xs ys : List Char) (w : List Step) (s : Int), wfaAlignF sc xs ys = some (w, s) → IsMonotoneWalk w xs ys ∧ walkScore sc xs ys w = s :=
  wfaAlignF_sound
#print axioms wfaAlignF_sound

example : ∀ (sc : Scoring) (xs ys : List Char), (wfaAlignF sc xs ys).isSome :=
  wfaAlignF_isSome
#print axioms wfaAlignF_isSome

-- ══ exported: kernel wfal (score) — statements pinned ══
example : ∀ (sc : Scoring) (xs ys : List Char), wfaAlignL sc xs ys = wfaAlign sc xs ys :=
  wfaAlignL_eq
#print axioms wfaAlignL_eq

example : ∀ (sc : Scoring) (xs ys : List Char), (wfaAlignL sc xs ys).map (fun r => r.2) = (getBestAlignment sc xs ys).map (fun r => r.2) :=
  wfaAlignL_score
#print axioms wfaAlignL_score

example : ∀ (sc : Scoring) (xs ys : List Char) (w : List Step) (s : Int), wfaAlignL sc xs ys = some (w, s) → IsMonotoneWalk w xs ys ∧ walkScore sc xs ys w = s :=
  wfaAlignL_sound
#print axioms wfaAlignL_sound

example : ∀ (sc : Scoring) (xs ys : List Char), (wfaAlignL sc xs ys).isSome :=
  wfaAlignL_isSome
#print axioms wfaAlignL_isSome

-- ── supporting (AlignmentWfaFused): fused level = nextLevelT ──
#check @nextLevelF_eq
#print axioms nextLevelF_eq

-- ── supporting (AlignmentWfaLazy): lazy candidate selection = two-push form ──
#check @stepPairX_eq
#print axioms stepPairX_eq
#check @stepPairY_eq
#print axioms stepPairY_eq
#check @stepDiag2_eq
#print axioms stepDiag2_eq

-- ── supporting (AlignmentWfaLazyLevel): lazy fused level = nextLevelT ──
#check @nextLevelL_eq
#print axioms nextLevelL_eq
#check @extendCellL_eq
#print axioms extendCellL_eq
#check @extOpt_eq
#print axioms extOpt_eq

-- ── supporting (AlignmentWfaFast): loops and runs of each variant = the proven ones ──
#check @nextLevelI_eq
#print axioms nextLevelI_eq
#check @wfaLoopI_eq
#print axioms wfaLoopI_eq
#check @wfaRunI_eq
#print axioms wfaRunI_eq
#check @wfaLoopF_eq
#print axioms wfaLoopF_eq
#check @wfaRunF_eq
#print axioms wfaRunF_eq
#check @wfaLoopL_eq
#print axioms wfaLoopL_eq
#check @wfaRunL_eq
#print axioms wfaRunL_eq
