import AlignmentWfaArray
import AlignmentWfaCertified
import AlignmentWfaDirect
import AlignmentWfaLcp
import AlignmentWfaOff
import AlignmentWfaOffLoop
import AlignmentWfaOffR
import AlignmentWfaPoint
import AlignmentWfaView
open AlignmentSpec

/-!
# Proof certificate: codec folder `wfa_offsets`

GENERATED by alignment/checks/gen_certificates.py — do not edit by hand.
Read the output of `lake env lean <this file>`: every `#check` line shows a
theorem statement, every `depends on axioms` line must list only propext,
Classical.choice, Quot.sound (never sorryAx).  `example` lines pin the
exported statements verbatim (they come from KERNEL_THEOREMS in
pabench/run_all.py, the table the comparison harness re-elaborates per commit).
* runner kernel `wfaca` (module `AlignmentWfaArray`): the codec's score equals the frozen optimum; every returned walk is a valid alignment carrying its true score; a result is always returned
* runner kernel `wfac` (module `AlignmentWfaCertified`): the codec's score equals the frozen optimum; every returned walk is a valid alignment carrying its true score; a result is always returned
-/

-- ══ exported: kernel wfaca (score) — statements pinned ══
example : ∀ (sc : Scoring) (xa ya : Array Char), (wfaAlignCA sc xa ya).map Prod.snd = (getBestAlignment sc xa.toList ya.toList).map Prod.snd :=
  wfaAlignCA_score
#print axioms wfaAlignCA_score

example : ∀ (sc : Scoring) (xa ya : Array Char) (w : List Step) (s : Int), wfaAlignCA sc xa ya = some (w, s) → IsMonotoneWalk w xa.toList ya.toList ∧ walkScore sc xa.toList ya.toList w = s :=
  wfaAlignCA_sound
#print axioms wfaAlignCA_sound

example : ∀ (sc : Scoring) (xa ya : Array Char), (wfaAlignCA sc xa ya).isSome :=
  wfaAlignCA_isSome
#print axioms wfaAlignCA_isSome

-- ══ exported: kernel wfac (score) — statements pinned ══
example : ∀ (sc : Scoring) (xs ys : List Char), (wfaAlignC sc xs ys).map (fun r => r.2) = (getBestAlignment sc xs ys).map (fun r => r.2) :=
  wfaAlignC_score
#print axioms wfaAlignC_score

example : ∀ (sc : Scoring) (xs ys : List Char) (w : List Step) (s : Int), wfaAlignC sc xs ys = some (w, s) → IsMonotoneWalk w xs ys ∧ walkScore sc xs ys w = s :=
  wfaAlignC_sound
#print axioms wfaAlignC_sound

example : ∀ (sc : Scoring) (xs ys : List Char), (wfaAlignC sc xs ys).isSome :=
  wfaAlignC_isSome
#print axioms wfaAlignC_isSome

-- ── supporting (AlignmentWfaOff): model level projects to the offsets-only level under the model invariant ──
#check @projL_nextLevel
#print axioms projL_nextLevel
#check @projL_seedLevel
#print axioms projL_seedLevel
#check @cornerOf_iff_cornerO
#print axioms cornerOf_iff_cornerO

-- ── supporting (AlignmentWfaOffLoop): corner level L determines the optimal score: 2 s + L = matchScore (m+n) ──
#check @wfaLoopO_spec
#print axioms wfaLoopO_spec
#check @wfaRunO_spec
#print axioms wfaRunO_spec

-- ── supporting (AlignmentWfaOffR): banded Nat-array fronts denote the offsets-only level ──
#check @rdenL_nextLevelR
#print axioms rdenL_nextLevelR
#check @rdenL_seedR
#print axioms rdenL_seedR
#check @cornerR_eq
#print axioms cornerR_eq

-- ── supporting (AlignmentWfaView): deferred array views materialize to the same fronts ──
#check @nextLevelV_eq
#print axioms nextLevelV_eq

-- ── supporting (AlignmentWfaDirect): generated direct scalar loops = the view algebra ──
#check @nextLevelD_eq
#print axioms nextLevelD_eq

-- ── supporting (AlignmentWfaPoint): pointwise absolute-diagonal recurrence = the banded-array recurrence ──
#check @nextLevelP_eq
#print axioms nextLevelP_eq
#check @packPointX_eq
#print axioms packPointX_eq
#check @packPointY_eq
#print axioms packPointY_eq
#check @packPointM_eq
#print axioms packPointM_eq

-- ── supporting (AlignmentWfaLcp): four-character LCP chunking (proved, not enabled) ──
#check @extChunkR_eq
#print axioms extChunkR_eq

-- ── supporting (AlignmentWfaCertified): executed loop = offsets loop; certificate ⇒ optimal score; checked walk ⇒ sound ──
#check @wfaLoopR_eq
#print axioms wfaLoopR_eq
#check @wfaRunR_eq
#print axioms wfaRunR_eq
#check @offsets_certify_score
#print axioms offsets_certify_score
#check @walkCheck_sound
#print axioms walkCheck_sound
#check @certifiedTraceR_spec
#print axioms certifiedTraceR_spec

-- ── supporting (AlignmentWfaArray): array-input execution refines the list kernel ──
#check @wfaRunArray_eq
#print axioms wfaRunArray_eq
#check @walkCheckA_eq
#print axioms walkCheckA_eq
#check @certifiedArray_eq
#print axioms certifiedArray_eq
#check @wfaAlignCA_eq
#print axioms wfaAlignCA_eq
