#!/usr/bin/env python3
"""Expand the proved NView algebra into three loops with scalar captures.
The generated Lean theorem proves exact equality; the generator is untrusted.
"""
from pathlib import Path
lines = []
counter = 0

def bind(e):
    global counter
    name = f'v{counter}'
    counter += 1
    lines.append(f'  let {name} := {e}')
    return name

def leaf(f):
    return (f'{f}.lo', f'{f}.body.size', lambda i: f'({f}.body[{i}]?).getD 0')

def mapped(g, f):
    lo, n, get = f
    return (lo, n, lambda i: f'{g} ({lo} + {i}) ({get(i)})')

def up(f):
    lo, n, get = f
    return (bind(f'{lo} + 1'), n, get)

def down(f):
    lo, n, get = f
    return (bind(f'{lo} - 1'), bind(f'if {lo} = 0 then min (1 + (len - 1)) {n} - 1 else if {n} ≤ len - {lo} then {n} else min (len - {lo}) {n}'),
            lambda i: get(f'(if {lo} = 0 then 1 + {i} else {i})'))

def zipped(f,g):
    fl, fn, fg = f; gl, gn, gg = g
    lo = bind(f'min {fl} {gl}')
    fp = bind(f'{fl} - {lo}'); gp = bind(f'{gl} - {lo}')
    outlo = bind(f'if {fn} = 0 then {gl} else if {gn} = 0 then {fl} else {lo}')
    size = bind(f'if {fn} = 0 then {gn} else if {gn} = 0 then {fn} else max ({fp} + {fn}) ({gp} + {gn})')
    def get(i):
        a = f'(if {i} < {fp} + {fn} then (if {i} < {fp} then 0 else {fg(f"({i} - {fp})")}) else 0)'
        b = f'(if {i} < {gp} + {gn} then (if {i} < {gp} then 0 else {gg(f"({i} - {gp})")}) else 0)'
        return f'(if {fn} = 0 then {gg(i)} else if {gn} = 0 then {fg(i)} else betterR {a} {b})'
    return outlo, size, get

def emit(name, f):
    lo,n,get = f
    lines.append(f'  let {name} : RFront := ⟨{lo}, arrayBuild (fun i : Fin {n} => {get("i.val")})⟩')
    return leaf(name)

def component(name, args, construct, spec):
    global lines, counter
    lines = []
    counter = 0
    construct()
    lines.append('  out')
    body = '\n'.join(lines)
    return f"def {name} {args} : RFront :=\n{body}\n\ntheorem {name}_eq {args} :\n    {name} " + {
        'directX': 'm n xe xo', 'directY': 'm n len ye yo',
        'directM': 'm n xa ya dm xf yf'}[name] + f" = {spec} := by\n  rfl\n\n"

xspec = 'packV (zipV (shiftUpV (mapV (pushXR m n) (viewR xe))) (shiftUpV (mapV (pushXR m n) (viewR xo))))'
yspec = 'packV (zipV (shiftDownV len (mapV (pushYR m n) (viewR ye))) (shiftDownV len (mapV (pushYR m n) (viewR yo))))'
mspec = 'packV (mapV (extR m xa ya) (zipV (zipV (mapV (pushDR m n) (viewR dm)) (viewR xf)) (viewR yf)))'
text = """import AlignmentWfaView

/-! Generated by generate_wfa_direct.py. Three materialized arrays, scalar
captures only. Each component is checked against the proved view algebra. -/
namespace AlignmentSpec
set_option maxHeartbeats 1000000
set_option maxRecDepth 10000

"""
text += component('directX', '(m n : Nat) (xe xo : RFront)',
    lambda: emit('out', zipped(up(mapped('pushXR m n',leaf('xe'))), up(mapped('pushXR m n',leaf('xo'))))), xspec)
text += component('directY', '(m n len : Nat) (ye yo : RFront)',
    lambda: emit('out', zipped(down(mapped('pushYR m n',leaf('ye'))), down(mapped('pushYR m n',leaf('yo'))))), yspec)
text += component('directM', '(m n : Nat) (xa ya : Array Char) (dm xf yf : RFront)',
    lambda: emit('out', mapped('extR m xa ya',zipped(zipped(mapped('pushDR m n',leaf('dm')),leaf('xf')),leaf('yf')))), mspec)
text += """def nextLevelD (m n : Nat) (xa ya : Array Char) (len pe po px : Nat)
    (hist : List RLevel) : RLevel :=
  let xf := directX m n (frontAtR hist pe (·.xf)) (frontAtR hist po (·.mf))
  let yf := directY m n len (frontAtR hist pe (·.yf)) (frontAtR hist po (·.mf))
  ⟨directM m n xa ya (frontAtR hist px (·.mf)) xf yf, xf, yf⟩

theorem nextLevelD_eq (m n : Nat) (xa ya : Array Char) (len pe po px : Nat)
    (hist : List RLevel) :
    nextLevelD m n xa ya len pe po px hist = nextLevelR m n xa ya len pe po px hist := by
  simp only [nextLevelD, directX_eq, directY_eq, directM_eq]
  exact nextLevelV_eq m n xa ya len pe po px hist

end AlignmentSpec
#print axioms AlignmentSpec.nextLevelD_eq
"""
Path(__file__).with_name('AlignmentWfaDirect.lean').write_text(text)
