import Init.Data.List.MinMaxOn

-- ════════════════════════════════════════════════════════════════════
-- PART 1: THE SPECIFICATION  (Rowan reads, checks, and owns this part)
--
-- Everything below up to the "PROOFS" banner is the contract.  It is
-- meant to be readable top to bottom with no proof knowledge: an
-- alignment is a list of steps, a valid alignment is one whose steps
-- consume exactly both input strings (the arithmetic predicate), the
-- score of an alignment is a single stateful walk, and the algorithm
-- enumerates every valid alignment, scores each, and keeps the best.
-- ════════════════════════════════════════════════════════════════════

namespace AlignmentSpec

-- One column of an alignment, i.e. one step of a monotone lattice path.
inductive Step where
  | diag  -- consume a letter from both strings (match or mismatch)
  | gapX  -- gap in x: consume a letter from y only (insertion)
  | gapY  -- gap in y: consume a letter from x only (deletion)
deriving Repr, BEq, DecidableEq

-- How many letters of x (respectively y) one step consumes.
def xConsumed : Step → Nat
  | .diag => 1
  | .gapY => 1
  | .gapX => 0

def yConsumed : Step → Nat
  | .diag => 1
  | .gapX => 1
  | .gapY => 0

-- The arithmetic validity predicate: a step list is a monotone lattice
-- path over xs and ys exactly when its steps consume all of xs and all
-- of ys.  Monotonicity itself is automatic, because every step moves
-- forward; the only thing that can go wrong is consuming too much or
-- too little, and that is what the two equations rule out.
def IsMonotoneWalk (path : List Step) (xs ys : List Char) : Prop :=
  (path.map xConsumed).sum = xs.length ∧
  (path.map yConsumed).sum = ys.length

-- The four scoring parameters.  A gap run of length k costs
-- gapOpen + k * gapExtend (the "o + k·e" convention): every gap column
-- pays gapExtend, and the first column of a run additionally pays
-- gapOpen.
structure Scoring where
  matchScore    : Int
  mismatchScore : Int
  gapOpen       : Int
  gapExtend     : Int

-- Walk one alignment along both strings and add up its score.  The
-- one piece of carried state, the previous step, is the entire content
-- of "affine": a gap column pays gapOpen exactly when the previous
-- column was not a gap in the same string.
--
-- The final catch-all case returns 0.  It is unreachable whenever the
-- path satisfies IsMonotoneWalk (a valid path never runs out of
-- letters early or late), and every theorem below only ever scores
-- valid paths, so the junk value never influences the contract.
def scoreWalk (sc : Scoring) :
    List Step → List Char → List Char → Option Step → Int
  | [], _, _, _ => 0
  | .diag :: rest, x :: xs, y :: ys, _ =>
      (if x = y then sc.matchScore else sc.mismatchScore)
        + scoreWalk sc rest xs ys (some .diag)
  | .gapX :: rest, xs, _ :: ys, prev =>
      (if prev = some .gapX then sc.gapExtend
       else sc.gapOpen + sc.gapExtend)
        + scoreWalk sc rest xs ys (some .gapX)
  | .gapY :: rest, _ :: xs, ys, prev =>
      (if prev = some .gapY then sc.gapExtend
       else sc.gapOpen + sc.gapExtend)
        + scoreWalk sc rest xs ys (some .gapY)
  | _, _, _, _ => 0

-- The score of a whole alignment, starting with no previous step.
def walkScore (sc : Scoring) (xs ys : List Char) (path : List Step) : Int :=
  scoreWalk sc path xs ys none

-- Every monotone lattice path over xs and ys, generated by branching
-- three ways at every position until both strings are exhausted.
def allPaths : List Char → List Char → List (List Step)
  | [], [] => [[]]
  | [], _ :: ys => (allPaths [] ys).map (Step.gapX :: ·)
  | _ :: xs, [] => (allPaths xs []).map (Step.gapY :: ·)
  | x :: xs, y :: ys =>
      ((allPaths xs ys).map (Step.diag :: ·)) ++
      ((allPaths (x :: xs) ys).map (Step.gapX :: ·)) ++
      ((allPaths xs (y :: ys)).map (Step.gapY :: ·))

-- The frozen reference algorithm: enumerate every alignment, score
-- each one, and return the best alignment together with its score.
-- Ties are broken by enumeration order (maxOn? keeps the earliest
-- maximum), so the tie policy is: diagonal before gap-in-x before
-- gap-in-y, decided at the earliest position where alignments differ.
def getBestAlignment (sc : Scoring) (xs ys : List Char) :
    Option (List Step × Int) :=
  ((allPaths xs ys).map fun path => (path, walkScore sc xs ys path)).maxOn?
    fun item => item.2

-- ════════════════════════════════════════════════════════════════════
-- WITNESSES  (small hand-checkable cases that keep the spec honest)
-- ════════════════════════════════════════════════════════════════════

def demoScoring : Scoring :=
  { matchScore := 2, mismatchScore := -1, gapOpen := -3, gapExtend := -1 }

-- The number of alignments of a 3-letter and a 4-letter string is the
-- Delannoy number D(3,4) = 129.
#guard (allPaths ['A','B','C'] ['A','B','B','C']).length == 129

-- Three matches (+6) plus one opened gap of length one (-4) gives 2,
-- via the alignment AB-C / ABBC.
#guard getBestAlignment demoScoring ['A','B','C'] ['A','B','B','C']
  == some ([.diag, .diag, .gapX, .diag], 2)

-- Two identical strings align with matches only.
#guard getBestAlignment demoScoring ['A','C','B'] ['A','C','B']
  == some ([.diag, .diag, .diag], 4 + 2)

-- Aligning against the empty string forces one gap run:
-- gapOpen + 2 * gapExtend = -5.
#guard getBestAlignment demoScoring [] ['A','B']
  == some ([.gapX, .gapX], -5)

-- Two empty strings have exactly one alignment, the empty one, score 0.
#guard getBestAlignment demoScoring [] [] == some ([], 0)

-- An affine sanity check: the two deletions come out adjacent, paying
-- gapOpen only once: two matches (+4) minus one run of two gaps
-- (-3 - 2*1 = -5) gives -1.  A linear gap cost could not distinguish
-- this alignment from one with two separated deletions.
#guard getBestAlignment demoScoring ['A','B','B','A'] ['A','A']
  == some ([.diag, .gapY, .gapY, .diag], -1)

-- ════════════════════════════════════════════════════════════════════
-- PART 2: PROOFS  (machine work; the theorems' statements are part of
-- the contract, their proofs are not meant to be read)
-- ════════════════════════════════════════════════════════════════════

-- ── The bridge: membership in allPaths is exactly IsMonotoneWalk ──

-- Soundness: everything the generator produces is a valid walk.
theorem isMonotoneWalk_of_mem_allPaths
    (xs ys : List Char) (path : List Step)
    (hmem : path ∈ allPaths xs ys) :
    IsMonotoneWalk path xs ys := by
  induction xs, ys using allPaths.induct generalizing path with
  | case1 =>
      simp [allPaths] at hmem
      simp [hmem, IsMonotoneWalk]
  | case2 y ys ih =>
      simp [allPaths] at hmem
      obtain ⟨q, hq, rfl⟩ := hmem
      have := ih q hq
      simp [IsMonotoneWalk, yConsumed, xConsumed] at this ⊢
      omega
  | case3 x xs ih =>
      simp [allPaths] at hmem
      obtain ⟨q, hq, rfl⟩ := hmem
      have := ih q hq
      simp [IsMonotoneWalk, yConsumed, xConsumed] at this ⊢
      omega
  | case4 x xs y ys ihDiag ihGapX ihGapY =>
      simp [allPaths] at hmem
      rcases hmem with ⟨q, hq, rfl⟩ | ⟨q, hq, rfl⟩ | ⟨q, hq, rfl⟩
      · have := ihDiag q hq
        simp [IsMonotoneWalk, yConsumed, xConsumed] at this ⊢
        omega
      · have := ihGapX q hq
        simp [IsMonotoneWalk, yConsumed, xConsumed] at this ⊢
        omega
      · have := ihGapY q hq
        simp [IsMonotoneWalk, yConsumed, xConsumed] at this ⊢
        omega

-- Completeness: every valid walk is generated.  This is the theorem
-- that keeps the enumeration honest: if allPaths silently skipped an
-- alignment, this proof would break.
theorem mem_allPaths_of_isMonotoneWalk
    (path : List Step) (xs ys : List Char)
    (hwalk : IsMonotoneWalk path xs ys) :
    path ∈ allPaths xs ys := by
  induction path generalizing xs ys with
  | nil =>
      obtain ⟨hx, hy⟩ := hwalk
      simp at hx hy
      cases xs with
      | nil =>
          cases ys with
          | nil => simp [allPaths]
          | cons y ys => simp at hy
      | cons x xs => simp at hx
  | cons s rest ih =>
      obtain ⟨hx, hy⟩ := hwalk
      cases s with
      | diag =>
          cases xs with
          | nil => simp [xConsumed] at hx
          | cons x xs =>
              cases ys with
              | nil => simp [yConsumed] at hy
              | cons y ys =>
                  simp [xConsumed, yConsumed] at hx hy
                  have hrest : rest ∈ allPaths xs ys := by
                    apply ih
                    constructor <;> omega
                  simp [allPaths]
                  exact hrest
      | gapX =>
          cases ys with
          | nil => simp [yConsumed] at hy
          | cons y ys =>
              simp [xConsumed, yConsumed] at hx hy
              have hrest : rest ∈ allPaths xs ys := by
                apply ih
                constructor <;> omega
              cases xs with
              | nil =>
                  simp [allPaths]
                  exact hrest
              | cons x xs =>
                  simp [allPaths]
                  exact hrest
      | gapY =>
          cases xs with
          | nil => simp [xConsumed] at hx
          | cons x xs =>
              simp [xConsumed, yConsumed] at hx hy
              have hrest : rest ∈ allPaths xs ys := by
                apply ih
                constructor <;> omega
              cases ys with
              | nil =>
                  simp [allPaths]
                  exact hrest
              | cons y ys =>
                  simp [allPaths]
                  exact hrest

-- The two directions packaged as one equivalence.
theorem mem_allPaths_iff_isMonotoneWalk
    (path : List Step) (xs ys : List Char) :
    path ∈ allPaths xs ys ↔ IsMonotoneWalk path xs ys :=
  ⟨isMonotoneWalk_of_mem_allPaths xs ys path,
   mem_allPaths_of_isMonotoneWalk path xs ys⟩

-- ── Non-vacuity ──

-- Two tiny arithmetic helpers for the witness path below.
private theorem sum_map_one (l : List Char) :
    (l.map fun _ => (1 : Nat)).sum = l.length := by
  induction l with
  | nil => rfl
  | cons a l ih => simp [ih]; omega

private theorem sum_map_zero (l : List Char) :
    (l.map fun _ => (0 : Nat)).sum = 0 := by
  induction l with
  | nil => rfl
  | cons a l ih => simp [ih]

-- The generator always produces at least one path (delete all of xs,
-- then insert all of ys), so the algorithm can never return none.
theorem allPaths_ne_nil (xs ys : List Char) : allPaths xs ys ≠ [] := by
  have hmem :
      (xs.map fun _ => Step.gapY) ++ (ys.map fun _ => Step.gapX) ∈
        allPaths xs ys := by
    apply mem_allPaths_of_isMonotoneWalk
    constructor <;>
      simp [Function.comp_def, xConsumed, yConsumed,
        sum_map_one, sum_map_zero]
  exact List.ne_nil_of_mem hmem

theorem getBestAlignment_returns_some
    (sc : Scoring) (xs ys : List Char) :
    ∃ best : List Step × Int,
      getBestAlignment sc xs ys = some best := by
  apply Option.isSome_iff_exists.mp
  rw [getBestAlignment, List.isSome_maxOn?_iff]
  simpa using allPaths_ne_nil xs ys

-- ── The returned pair is a real, correctly scored alignment ──

theorem getBestAlignment_returns_a_valid_walk
    (sc : Scoring) (xs ys : List Char)
    (bestPath : List Step) (bestScore : Int)
    (hreturned : getBestAlignment sc xs ys = some (bestPath, bestScore)) :
    IsMonotoneWalk bestPath xs ys ∧
    walkScore sc xs ys bestPath = bestScore := by
  have hmem := List.maxOn?_mem hreturned
  obtain ⟨path, hpath, hpair⟩ := List.mem_map.mp hmem
  have hfst : path = bestPath := congrArg Prod.fst hpair
  have hsnd : walkScore sc xs ys path = bestScore := congrArg Prod.snd hpair
  subst hfst
  exact ⟨isMonotoneWalk_of_mem_allPaths xs ys path hpath, hsnd⟩

-- ── Optimality: no valid alignment scores higher than the returned one ──

theorem getBestAlignment_returns_a_maximum_score
    (sc : Scoring) (xs ys : List Char)
    (bestPath : List Step) (bestScore : Int)
    (candidate : List Step)
    (hreturned : getBestAlignment sc xs ys = some (bestPath, bestScore))
    (hcandidate : IsMonotoneWalk candidate xs ys) :
    walkScore sc xs ys candidate ≤ bestScore := by
  have hcmem : candidate ∈ allPaths xs ys :=
    mem_allPaths_of_isMonotoneWalk candidate xs ys hcandidate
  have hcpair :
      (candidate, walkScore sc xs ys candidate) ∈
        (allPaths xs ys).map fun path => (path, walkScore sc xs ys path) :=
    List.mem_map.mpr ⟨candidate, hcmem, rfl⟩
  have hle :=
    List.le_apply_maxOn_of_mem
      (f := fun item : List Step × Int => item.2)
      hcpair
  rw [List.maxOn_eq_of_maxOn?_eq_some hreturned] at hle
  exact hle

end AlignmentSpec
