import AlignmentLexicographic
import AlignmentSpec
open AlignmentSpec

/-!
# Proof certificate: frozen alignment specification

GENERATED by alignment/checks/gen_certificates.py — do not edit by hand.
Read the output of `lake env lean <this file>`: every `#check` line shows a
theorem statement, every `depends on axioms` line must list only propext,
Classical.choice, Quot.sound (never sorryAx).  `example` lines pin the
exported statements verbatim (they come from KERNEL_THEOREMS in
pabench/run_all.py, the table the comparison harness re-elaborates per commit).
-/

-- ── supporting (AlignmentSpec): what the frozen specification guarantees about itself ──
#check @getBestAlignment_returns_some
#print axioms getBestAlignment_returns_some
#check @getBestAlignment_returns_a_valid_walk
#print axioms getBestAlignment_returns_a_valid_walk
#check @getBestAlignment_returns_a_maximum_score
#print axioms getBestAlignment_returns_a_maximum_score
#check @mem_allPaths_iff_isMonotoneWalk
#print axioms mem_allPaths_iff_isMonotoneWalk

-- ── supporting (AlignmentLexicographic): the frozen tie rule: the returned path is the lexicographically least optimal path ──
#check @getBestAlignment_lex_least
#print axioms getBestAlignment_lex_least
#check @getBestAlignment_characterization
#print axioms getBestAlignment_characterization
