import AlignmentCigarCheck
import AlignmentCigarCheckFast
import AlignmentWfaRuns
import AlignmentWfaRunsFast
import AlignmentWfaRunsVsWfa
open AlignmentSpec

/-!
# Proof certificate: codec folder `wfa_runs`

GENERATED by alignment/checks/gen_certificates.py — do not edit by hand.
Read the output of `lake env lean <this file>`: every `#check` line shows a
theorem statement, every `depends on axioms` line must list only propext,
Classical.choice, Quot.sound (never sorryAx).  `example` lines pin the
exported statements verbatim (they come from KERNEL_THEOREMS in
pabench/run_all.py, the table the comparison harness re-elaborates per commit).
* runner kernel `wfak` (module `AlignmentWfaRuns`): the codec's score equals the frozen optimum; every returned walk is a valid alignment carrying its true score; a result is always returned
* runner kernel `wfakf` (module `AlignmentWfaRunsFast`): the codec's score equals the frozen optimum; every returned walk is a valid alignment carrying its true score; a result is always returned
-/

-- ══ exported: kernel wfak (score) — statements pinned ══
example : ∀ (sc : Scoring) (xa ya : Array Char), (wfaAlignK sc xa ya).map Prod.snd = (getBestAlignment sc xa.toList ya.toList).map Prod.snd :=
  wfaAlignK_score
#print axioms wfaAlignK_score

example : ∀ (sc : Scoring) (xa ya : Array Char) (c : Array (Step × Nat)) (s : Int), wfaAlignK sc xa ya = some (c, s) → IsMonotoneWalk (expandCigar c) xa.toList ya.toList ∧ walkScore sc xa.toList ya.toList (expandCigar c) = s :=
  wfaAlignK_sound
#print axioms wfaAlignK_sound

example : ∀ (sc : Scoring) (xa ya : Array Char), (wfaAlignK sc xa ya).isSome :=
  wfaAlignK_isSome
#print axioms wfaAlignK_isSome

-- ══ exported: kernel wfakf (score) — statements pinned ══
example : ∀ (sc : Scoring) (xa ya : Array Char), (wfaAlignKF sc xa ya).map Prod.snd = (getBestAlignment sc xa.toList ya.toList).map Prod.snd :=
  wfaAlignKF_score
#print axioms wfaAlignKF_score

example : ∀ (sc : Scoring) (xa ya : Array Char) (c : Array (Step × Nat)) (s : Int), wfaAlignKF sc xa ya = some (c, s) → IsMonotoneWalk (expandCigar c) xa.toList ya.toList ∧ walkScore sc xa.toList ya.toList (expandCigar c) = s :=
  wfaAlignKF_sound
#print axioms wfaAlignKF_sound

example : ∀ (sc : Scoring) (xa ya : Array Char), (wfaAlignKF sc xa ya).isSome :=
  wfaAlignKF_isSome
#print axioms wfaAlignKF_isSome

-- ── supporting (AlignmentCigarCheck): scalar run checker is sound ──
#check @checkRepeatFast_eq
#print axioms checkRepeatFast_eq
#check @checkRuns_check
#print axioms checkRuns_check
#check @checkRuns_sound
#print axioms checkRuns_sound

-- ── supporting (AlignmentWfaRuns): certified direct-run traceback ──
#check @certifiedRuns_spec
#print axioms certifiedRuns_spec

-- ── supporting (AlignmentCigarCheckFast): faster run checker (USize scan), proven equal to checkRuns ──
#check @checkRunsFast3_eq
#print axioms checkRunsFast3_eq
#check @checkRunsFast3_sound
#print axioms checkRunsFast3_sound

-- ── supporting (AlignmentWfaRunsFast): wfaAlignKF = wfaAlignK with the fast checker (same function) ──
#check @certifiedRunsF_eq
#print axioms certifiedRunsF_eq
#check @wfaAlignKF_eq
#print axioms wfaAlignKF_eq

-- ── supporting (AlignmentWfaRunsVsWfa): function equality with the proven wfaAlign (scores) ──
#check @wfaAlignK_score_eq_wfaAlign
#print axioms wfaAlignK_score_eq_wfaAlign
#check @wfaAlignCA_score_eq_wfaAlign
#print axioms wfaAlignCA_score_eq_wfaAlign
#check @wfaAlignK_score_fun_eq
#print axioms wfaAlignK_score_fun_eq
