#!/usr/bin/env python3
"""Derive a run-emitting traceback candidate from traceR.

This generator is not trusted. Every candidate must pass the proved run
checker and optimal-offset certificate, or the exact fallback is used.
"""
from pathlib import Path
root = Path(__file__).resolve().parent
src = (root.parent / "wfa_offsets" / "AlignmentWfaCertified.lean").read_text()
src = src[src.index("def traceR ("):src.index("/-- Check consumption")].strip()
src = src.replace("def traceR (", "def traceRuns (")
src = src.replace(": List Step", ": List (Step × Nat)")
old = """      let mut k := off - b
      while k > 0 do
        w := .diag :: w; k := k - 1"""
new = """      let k := off - b
      if k > 0 then w := (.diag, k.toNat) :: w"""
assert old in src
src = src.replace(old, new)
src = src.replace("else w := .diag :: (demoteWalk w).getD w   -- rejected by the certificate if boundary surgery is needed",
                  "else return [] -- request exact fallback when boundary surgery would be needed")
for s in ["diag", "gapX", "gapY"]:
    src = src.replace(f"w := .{s} :: w", f"w := (.{s}, 1) :: w")
(root / "AlignmentTraceRuns.lean").write_text("""import AlignmentCigarCheck

/-! Generated by generate_run_trace.py. Offset traceback emits whole diagonal
runs. Acceptance requires the run checker and an optimal-score certificate.
The underlying offset traceback follows WFA2; see AlignmentWfaCertified.lean.
-/
namespace AlignmentSpec
""" + src + "\n\nend AlignmentSpec\n")
