import AlignmentWavefront
open AlignmentSpec

/-!
# Proof certificate: codec folder `band`

GENERATED by alignment/checks/gen_certificates.py — do not edit by hand.
Read the output of `lake env lean <this file>`: every `#check` line shows a
theorem statement, every `depends on axioms` line must list only propext,
Classical.choice, Quot.sound (never sorryAx).  `example` lines pin the
exported statements verbatim (they come from KERNEL_THEOREMS in
pabench/run_all.py, the table the comparison harness re-elaborates per commit).
* runner kernel `band` (module `AlignmentWavefront`): the codec's result (walk and score) EQUALS the frozen specification's result
-/

-- ══ exported: kernel band (equality) — statements pinned ══
example : ∀ (sc : Scoring) (xs ys : List Char), bandDoublingAlign sc xs ys = getBestAlignment sc xs ys :=
  bandDoublingAlign_equals_getBestAlignment
#print axioms bandDoublingAlign_equals_getBestAlignment

-- ── supporting (AlignmentWavefront): banded DP = spec inside the band; band doubling certified by the off-band bound ──
#check @penalty_transform
#print axioms penalty_transform
#check @score_le_iff_penalty_ge
#print axioms score_le_iff_penalty_ge
#check @bandedBestAux_eq_bBellman
#print axioms bandedBestAux_eq_bBellman
#check @bandedRun_eq
#print axioms bandedRun_eq
#check @two_score_le_offBandBound
#print axioms two_score_le_offBandBound
#check @certified_global
#print axioms certified_global
#check @bandDoublingGo_eq
#print axioms bandDoublingGo_eq
